version: '3.6'
services: 
  # proxy:
  #   volumes:
  #     - ./volumes/data/certbot/conf:/etc/letsencrypt
  #     - ./volumes/data/certbot/www:/var/www/certbot
  #   build: ./proxy
  #   restart: always
  #   networks:
  #     - intact_mass
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on: 
  #     - api
  #     - ui
  # eworkbook:
  #   build: ./eworkbook
  #   command: python app.py production
  #   ports: 
  #     - 3333:3333 
  #   networks:
  #     - intact_mass
  api:
    build: ./backend
    depends_on:
      - db 
    env_file:
      - ./backend/intact_server/.env
    command: python manage.py production
    volumes:
      - ./volumes/static:/intact_server/static
    ports:
        - 5000:5000
    restart: always
    networks: 
      - intact_mass
  # small:
  #   build: ./Small_services
  #   command: python app.py production
  #   ports: 
  #     - 4500:4500 
  #   restart: always
  #   networks: 
  #     - intact_mass 
  ui:
    build: ./frontend
    depends_on: 
      - api
    command: serve -s build
    restart: always
    ports:
      - 3000:3000
    networks:
      - intact_mass
  db:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1lUZkt2tF3BUZ0ch
      POSTGRES_DB: lonza
    image: postgres:13-alpine 
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - intact_mass 
networks:
  intact_mass: